name: DeepSeek Desktop App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Set Up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Universe Repository (Ubuntu Only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo add-apt-repository universe
          sudo apt-get update

      - name: Install Dependencies (Ubuntu Only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Project Dependencies
        run: npm install

      - name: Fix Permissions for Tauri CLI
        run: chmod +x ./node_modules/.bin/tauri

      - name: Build and Release Application
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: tauri-apps/tauri-action@v0
        with:
          tagName: v1.0.0
          releaseName: Release v1.0.0
          releaseBody: 'Automated release of DeepSeek Desktop App for all platforms'
          releaseDraft: false
          prerelease: false
